### ISSUE TITLE
Custer is not working on some url

### ISSUE THREAD

**Issue by mrvkino** [exelban/custer#1]
Hi,

I am trying to listen to [Radio-Canada Premiere](radio-canada.ca/premiere) with this url (http://cbcmp3.ic.llnwd.net/stream/cbcmp3_P-2QMTL0_MTL). It works on IINA and Safari but Custer pops an error message.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/279511/100903008-6c7e8580-3493-11eb-953e-a22b11bdfcb1.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting. 
It looks like I forgot to release a new version with this fix. Will be in a few minutes.

**Comment by exelban** [comment]
Done, a new release with this fix [available](https://github.com/exelban/custer/releases/tag/v1.1.0).

**Comment by mrvkino** [comment]
Yowza! That was fast! It works.

I also found this wonderful gem of a website (http://fmstream.org/index.php) that allowed me to find an alternate in the meantime.

Now, both stream works.

Thanks

**Comment by exelban** [comment]
It was fixed some time ago. I just forget to release a new version with it(
