### ISSUE TITLE
Respond to media key

### ISSUE THREAD

**Issue by mrvkino** [exelban/custer#2]
Hi,

it would be nice to have control of the app with the media key of macOS and if the play status could show in the now playing widget.

Thanks

**Comment by exelban** [comment]
Hmm. 
Yeap, I could add control of the app with media keys.

Now playing - you mean now playing song or program?

**Comment by mrvkino** [comment]
I was talking about the macOS widget in the Notification Center (https://support.apple.com/en-ca/guide/mac-help/mchl2fb1258f/mac) that you can swipe over:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/279511/100907317-2c6dd180-3498-11eb-9495-162c5aabe67d.png">

**Comment by exelban** [comment]
Ohh, my mistake)
Yeap, I think it could be added too. But will be better to have a separate issue for the widget.

**Comment by mrvkino** [comment]
Ok. Will do.
