### ISSUE TITLE
Show play status in the now playing notification status widget

### ISSUE THREAD

**Issue by mrvkino** [exelban/custer#3]
Showing the status of Custer in the now playing would be nice. This would allow any third party (like BetterTouchTool) to show the status and control the app (I think).

Example of Spotify showing up. 
![](https://user-images.githubusercontent.com/279511/100907317-2c6dd180-3498-11eb-9495-162c5aabe67d.png)

**Comment by exelban** [comment]
Hi.
There are 2 problems with implementation:
- it will not fit in the menu bar (and I want to keep it clean as possible)
- a lot of stream does not provide information about playing a song
