### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by mtklr** [exelban/custer#8]
Curious why this is called "custer", as that name has some negative associations? [wp custer](https://en.m.wikipedia.org/wiki/George_Armstrong_Custer)

**Comment by exelban** [comment]
hah. I just need a name for the app)
I don't know that someone with that surname lived.

Do you have a better name?

**Comment by mtklr** [comment]
Hi, thanks for your response. I hope that didn't come across as jumping on you about it, i really was only curious.

The only thing i can think of at the moment is "Hz" (abbreviation for Hertz measurement) or something audio/radio related. (Several "Custard" projects already exist)... If something inspiring hits me I'll let you know.:)

Thanks again.

**Comment by exelban** [comment]
Hz it's too short for the app name. Yeap, feel free to catch me if you will have a new name for the app.
